#Clone and build app
FROM golang:rc as GO
WORKDIR /app
ARG TRAVIS_BRANCH=$TRAVIS_BRANCH
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PORT=8080
RUN apt update && apt upgrade -y && apt install -y git 
RUN git clone https://github.com/dangerous-tech/MPGSMerchantServer /app
#Checkout staging if required
RUN if [ "${TRAVIS_BRANCH}" = "staging" ]; then git checkout staging; fi
RUN go build -v .

#Run app in thin container
FROM alpine:latest
WORKDIR /app
ENV PORT=8080
COPY --from=GO /app/mpgsmerchantserver .
ENTRYPOINT ["./mpgsmerchantserver"]
